# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def import_pods
    pod 'lf', '~> 0.5.0'
end

target 'BroadcaseExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
import_pods
  # Pods for BroadcaseExtension

end

target 'BroadcaseExtensionUI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BroadcaseExtensionUI

end

target 'ReplayKit-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReplayKit-Swift

end
