# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BroadcastUploadExtension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BroadcastUploadExtension

end

target 'BroadcastUploadExtensionUI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BroadcastUploadExtensionUI

end

target 'ReplayKitTutorial-ObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

  # Pods for ReplayKitTutorial-ObjC
pod 'lf', '~> 0.5.0'
end
